version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - binaryen
  - cdylib
  - direnv
  - drei
  - esbuild
  - GLTF
  - kwaa
  - moeru
  - nixpkgs
  - pixiv
  - pkgs
  - sonarjs
  - vite
  - vitejs
  - vitepress
  - viverse
  - XPBD
  - yuru
  - yurujs
ignoreWords: []
import: []
